baseURL = "https://readyforcommons.com/"
languageCode = "en-us"
title = "Ready for commons"

#Github pages
publishDir = "docs"

theme = "r4c"

[params]
  payoff = "Deliver FAIR content"
  author = "OSD opensensorsdata"
  author_description = "Data asset management"
  description = "This is the Ready for commons site"
  location = "Venezia, Italy"
  copyright = "2018 Ready for commons by [OSD](https://osd.tools)"
  images = ["img/seo/r4c-opg-facebook.png"]
  title = "Ready for commons"
